# Generated by Django 3.1.5 on 2021-04-04 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.CharField(default='', max_length=10000)),
                ('test_path', models.CharField(default='', max_length=100)),
                ('train_path', models.CharField(default='', max_length=100)),
                ('test_prediction_path', models.CharField(default='', max_length=100)),
                ('train_prediction_path', models.CharField(default='', max_length=100)),
                ('calculation_errors', models.CharField(default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
